// Every user-visible text lives here (es-MX, SPEC glossary vocabulary).
export const t = {
  appName: 'LabQR',

  tabs: {
    home: 'Inicio',
    scan: 'Escanear',
    items: 'Artículos',
    loans: 'Vales',
  },

  menu: {
    open: 'Abrir menú',
    title: 'Menú',
    settings: 'Ajustes',
    labels: 'Etiquetas',
    backup: 'Respaldo',
  },

  common: {
    back: 'Regresar',
    save: 'Guardar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Eliminar',
    add: 'Agregar',
    all: 'Todos',
    none: 'Sin asignar',
    yes: 'Sí',
    confirm: 'Confirmar',
  },

  kinds: {
    equipment: 'Equipo',
    material: 'Material',
    reagent: 'Reactivo',
  },

  kindHelp: {
    equipment: 'Pieza única, con número de serie. Cantidad siempre 1.',
    material: 'Piezas que se prestan y pueden romperse: vidrio, pinzas…',
    reagent: 'Se gasta en la práctica. Lleva unidad y caducidad.',
  },

  units: { pz: 'piezas', ml: 'ml', l: 'litros', g: 'gramos', kg: 'kilos' },

  movementTypes: {
    RECEIVE: 'Recepción',
    LEND: 'Préstamo',
    RETURN: 'Devolución',
    CONSUME: 'Consumo',
    LOSS: 'Merma',
    ADJUST: 'Ajuste por conteo',
  },

  home: {
    title: 'Inicio',
    empty: 'Aún no hay artículos. Carga la demo o agrega el primero.',
    loadDemo: 'Cargar demo',
    addItem: 'Agregar artículo',
    allLabs: 'Todos los laboratorios',
    low: (n) => `${n} bajo mínimo`,
    expiring: (n) => `${n} por caducar`,
    expired: (n) => `${n} ${n === 1 ? 'caducado' : 'caducados'}`,
    itemsWord: (n) => (n === 1 ? 'artículo' : 'artículos'),
    lent: (n) => `${n} con piezas prestadas`,
    allGood: 'Todo en orden',
    loansSoon: 'Los vales abiertos y vencidos aparecen aquí a partir de la fase 3.',
  },

  scan: {
    title: 'Escanear',
    aim: 'Apunta a la etiqueta del artículo',
    starting: 'Abriendo la cámara…',
    manual: 'Escribir código',
    manualPh: 'Ej. QUI-0007 o qui 7',
    open: 'Abrir ficha',
    notCode: 'Ese QR no es de LabQR. Acerca una etiqueta de artículo o escribe el código a mano.',
    notFound: (code) => `No existe un artículo con el código ${code}. Revisa la etiqueta o escríbelo a mano.`,
    badInput: 'Escribe un código como QUI-0007.',
    denied: 'No hay permiso para usar la cámara. Actívalo en los permisos del navegador para este sitio, o escribe el código a mano.',
    noCamera: 'No se encontró una cámara. Escribe el código a mano.',
    failed: 'No se pudo abrir la cámara. Cierra otras apps que la usen y vuelve a intentar, o escribe el código a mano.',
    retry: 'Reintentar',
  },

  labels: {
    title: 'Etiquetas',
    intro: 'Elige los artículos y toca Imprimir. Usa hojas carta; en la ventana de impresión elige escala 100 % y sin márgenes extra.',
    lab: 'Laboratorio',
    location: 'Ubicación',
    all: 'Todas',
    selectAll: 'Todos los de esta vista',
    selectNone: 'Ninguno',
    layout: 'Tamaño',
    large: 'Grande · 10 por hoja',
    small: 'Chica · 24 por hoja',
    selected: (n) => `${n} ${n === 1 ? 'etiqueta' : 'etiquetas'}`,
    sheets: (n) => `${n} ${n === 1 ? 'hoja' : 'hojas'}`,
    print: 'Imprimir',
    empty: 'Aún no hay artículos. Carga la demo o agrega el primero.',
    none: 'Marca al menos un artículo para imprimir.',
    preview: 'Vista previa',
  },

  loans: {
    title: 'Vales',
    empty: 'La pantalla de vales llega en la fase 3. La demo ya trae 3 vales que aparecerán aquí.',
  },

  items: {
    title: 'Artículos',
    empty: 'Aún no hay artículos. Carga la demo o agrega el primero.',
    noResults: 'Ningún artículo coincide. Cambia la búsqueda o quita filtros.',
    search: 'Buscar por nombre, código o dato',
    filterLab: 'Laboratorio',
    filterLocation: 'Ubicación',
    filterKind: 'Tipo',
    low: 'Bajo mínimo',
    expiring: 'Por caducar',
    archived: 'Archivados',
    count: (n) => `${n} ${n === 1 ? 'artículo' : 'artículos'}`,
    add: 'Agregar artículo',
    clear: 'Quitar filtros',
  },

  stock: {
    inLab: 'en lab',
    lent: 'prestados',
    total: 'total',
    min: 'mín',
    inPlace: 'En su lugar',
    lentTo: (who) => `Prestado a ${who}`,
    lentUnknown: 'Prestado',
    lost: 'Dado de baja',
    low: 'Bajo mínimo',
    expired: 'Caducado',
    expiring: 'Por caducar',
  },

  itemCard: {
    title: 'Ficha del artículo',
    notFound: (code) => `No existe un artículo con el código ${code}. Revisa la etiqueta o escríbelo a mano.`,
    data: 'Datos',
    lab: 'Laboratorio',
    location: 'Ubicación',
    serial: 'Número de serie',
    expires: 'Caduca',
    notes: 'Notas',
    extra: 'Especificaciones',
    extraEmpty: 'Sin especificaciones. Agrega las que pida el maestro: marca, modelo, concentración…',
    extraKey: 'Dato',
    extraValue: 'Valor',
    extraAdd: 'Agregar dato',
    extraSaved: 'Dato guardado',
    extraRemoved: 'Dato quitado',
    history: 'Historial',
    historyEmpty: 'Sin movimientos todavía.',
    by: (who) => `Responsable: ${who}`,
    loan: (practice) => `Vale: ${practice}`,
    actionsSoon: 'Recepción, merma y ajuste llegan en la fase 3.',
    printLabel: 'Imprimir etiqueta',
    archive: 'Archivar',
    unarchive: 'Quitar de archivados',
    archivedNote: 'Artículo archivado: no aparece en la lista ni en los conteos.',
    archiveQ: '¿Archivar este artículo? Deja de aparecer en la lista, pero su historial se conserva.',
    archivedToast: 'Artículo archivado',
    unarchivedToast: 'Artículo de regreso en la lista',
    deleteQ: '¿Eliminar este artículo? No tiene movimientos, así que se borra por completo.',
    deletedToast: 'Artículo eliminado',
  },

  itemForm: {
    newTitle: 'Nuevo artículo',
    editTitle: 'Editar artículo',
    name: 'Nombre',
    namePh: 'Ej. Vaso de precipitado 250 ml',
    kind: 'Tipo',
    lab: 'Laboratorio',
    location: 'Ubicación',
    unit: 'Unidad',
    initialQty: 'Cantidad que hay hoy',
    initialQtyHelp: 'Se registra como recepción. Después, la existencia solo cambia con movimientos.',
    minStock: 'Mínimo',
    minStockHelp: 'Si la existencia baja de aquí, se marca en rojo. Deja 0 si no aplica.',
    expiresAt: 'Fecha de caducidad',
    serial: 'Número de serie',
    notes: 'Notas',
    codeNote: (code) => `Código ${code}. No cambia porque va impreso en la etiqueta.`,
    codeNew: (prefix) => `El código se genera solo: ${prefix}-0000.`,
    needLab: 'Primero agrega un laboratorio en Ajustes.',
    goSettings: 'Ir a Ajustes',
    errName: 'Escribe el nombre del artículo.',
    errQty: 'Escribe una cantidad válida, por ejemplo 12 o 2.5.',
    saved: 'Artículo guardado',
    created: (code) => `Artículo ${code} agregado`,
  },

  settings: {
    title: 'Ajustes',
    labs: 'Laboratorios',
    labName: 'Nombre',
    labNamePh: 'Ej. Química',
    labPrefix: 'Prefijo',
    labPrefixPh: 'QUI',
    labPrefixHelp: 'De 2 a 5 letras. Va al inicio de cada código (QUI-0001).',
    labPrefixLocked: 'El prefijo ya no cambia: hay artículos con etiquetas impresas.',
    addLab: 'Agregar laboratorio',
    labSaved: 'Laboratorio guardado',
    labDeleteQ: '¿Eliminar este laboratorio y sus ubicaciones?',
    labDeleted: 'Laboratorio eliminado',
    labInUse: 'Ese laboratorio tiene artículos. Muévelos o archívalos antes de eliminarlo.',
    errLab: 'Escribe el nombre y un prefijo de 2 a 5 letras.',
    errPrefixTaken: 'Ese prefijo ya lo usa otro laboratorio.',
    locations: 'Ubicaciones',
    locationPh: 'Ej. Anaquel B · Gaveta 2',
    addLocation: 'Agregar ubicación',
    locationSaved: 'Ubicación guardada',
    locationDeleted: 'Ubicación eliminada',
    locationInUse: 'Esa ubicación tiene artículos. Cámbialos de lugar antes de eliminarla.',
    noLabs: 'Aún no hay laboratorios. Agrega el primero o carga la demo.',
    loanDays: 'Días de préstamo por defecto',
    loanDaysHelp: '0 = se devuelve el mismo día.',
    loanDaysSaved: 'Días de préstamo guardados',
    demo: 'Datos de demostración',
    demoHelp: 'Crea Química y Biología con 33 artículos, 5 solicitantes y 3 vales para enseñar la app.',
    demoLoad: 'Cargar datos de demostración',
    demoOnlyEmpty: 'La demo solo se carga con la app vacía. Usa "Borrar todo" primero.',
    demoLoaded: (n) => `Demo cargada: ${n} artículos`,
    wipe: 'Borrar todo',
    wipeHelp: 'Elimina todos los datos de este dispositivo. No se puede deshacer.',
    wipeType: 'Escribe BORRAR para confirmar',
    wipeWord: 'BORRAR',
    wipeQ: '¿Borrar todos los datos de este dispositivo? No se puede deshacer.',
    wipeConfirm: 'Borrar todos los datos',
    wipeDone: 'Se borraron todos los datos',
    storage: 'Datos en este dispositivo',
    storageReady: 'Base de datos lista',
    storageError: 'No se pudo abrir la base de datos. Cierra otras pestañas de LabQR y vuelve a abrirla.',
    offlineReady: 'Lista para usarse sin internet',
    offlinePending: 'Preparando uso sin internet…',
  },

  pending: {
    title: 'En construcción',
    body: 'Esta pantalla llega en una fase siguiente.',
  },

  notFound: {
    title: 'Página no encontrada',
    body: 'Esa dirección no existe en LabQR.',
    back: 'Ir a Inicio',
  },

  version: (v, built) => `Versión ${v} · ${built}`,
};
