// Every user-visible text lives here (es-MX, SPEC glossary vocabulary).
export const t = {
  appName: 'C-Lab',

  tabs: {
    home: 'Inicio',
    scan: 'Escanear',
    items: 'Artículos',
    loans: 'Vales',
  },

  menu: {
    open: 'Abrir menú',
    title: 'Menú',
    settings: 'Ajustes',
    labels: 'Etiquetas',
    backup: 'Respaldo',
    board: 'Tablero de exposición',
    practices: 'Prácticas',
  },

  common: {
    back: 'Regresar',
    save: 'Guardar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Eliminar',
    add: 'Agregar',
    all: 'Todos',
    none: 'Sin asignar',
    yes: 'Sí',
    confirm: 'Confirmar',
  },

  kinds: {
    equipment: 'Equipo',
    material: 'Material',
    reagent: 'Reactivo',
  },

  kindHelp: {
    equipment: 'Pieza única, con número de serie. Cantidad siempre 1.',
    material: 'Piezas que se prestan y pueden romperse: vidrio, pinzas…',
    reagent: 'Se gasta en la práctica. Lleva unidad y caducidad.',
  },

  units: { pz: 'piezas', ml: 'ml', l: 'litros', g: 'gramos', kg: 'kilos' },

  movementTypes: {
    RECEIVE: 'Recepción',
    LEND: 'Préstamo',
    RETURN: 'Devolución',
    CONSUME: 'Consumo',
    LOSS: 'Merma',
    ADJUST: 'Ajuste por conteo',
  },

  home: {
    title: 'Inicio',
    empty: 'Aún no hay artículos. Carga la demo o agrega el primero.',
    loadDemo: 'Cargar demo',
    addItem: 'Agregar artículo',
    allLabs: 'Todos los laboratorios',
    low: (n) => `${n} bajo mínimo`,
    expiring: (n) => `${n} por caducar`,
    expired: (n) => `${n} ${n === 1 ? 'caducado' : 'caducados'}`,
    itemsWord: (n) => (n === 1 ? 'artículo' : 'artículos'),
    lent: (n) => `${n} con piezas prestadas`,
    allGood: 'Todo en orden',
    openLoans: (n) => `${n} ${n === 1 ? 'vale abierto' : 'vales abiertos'}`,
    overdueLoans: (n) => `${n} ${n === 1 ? 'vale vencido' : 'vales vencidos'}`,
    newLoan: 'Nuevo vale',
  },

  scan: {
    title: 'Escanear',
    aim: 'Apunta a la etiqueta del artículo',
    starting: 'Abriendo la cámara…',
    manual: 'Escribir código',
    manualPh: 'Ej. QUI-0007 o qui 7',
    open: 'Abrir ficha',
    notCode: 'Ese QR no es de C-Lab. Acerca una etiqueta de artículo o escribe el código a mano.',
    notFound: (code) => `No existe un artículo con el código ${code}. Revisa la etiqueta o escríbelo a mano.`,
    badInput: 'Escribe un código como QUI-0007.',
    denied: 'No hay permiso para usar la cámara. Actívalo en los permisos del navegador para este sitio, o escribe el código a mano.',
    noCamera: 'No se encontró una cámara. Escribe el código a mano.',
    failed: 'No se pudo abrir la cámara. Cierra otras apps que la usen y vuelve a intentar, o escribe el código a mano.',
    retry: 'Reintentar',
  },

  labels: {
    title: 'Etiquetas',
    intro: 'Elige los artículos y toca Imprimir. Usa hojas carta; en la ventana de impresión elige escala 100 % y sin márgenes extra.',
    lab: 'Laboratorio',
    location: 'Ubicación',
    all: 'Todas',
    selectAll: 'Todos los de esta vista',
    selectNone: 'Ninguno',
    layout: 'Tamaño',
    large: 'Grande · 10 por hoja',
    small: 'Chica · 24 por hoja',
    selected: (n) => `${n} ${n === 1 ? 'etiqueta' : 'etiquetas'}`,
    sheets: (n) => `${n} ${n === 1 ? 'hoja' : 'hojas'}`,
    print: 'Imprimir',
    empty: 'Aún no hay artículos. Carga la demo o agrega el primero.',
    none: 'Marca al menos un artículo para imprimir.',
    preview: 'Vista previa',
  },

  loans: {
    title: 'Vales',
    empty: 'Aún no hay vales. Toca "Nuevo vale" cuando entregues material para una práctica.',
    emptyFilter: 'No hay vales en esta vista.',
    newLoan: 'Nuevo vale',
    open: 'Abiertos',
    closed: 'Cerrados',
    overdue: 'Vencidos',
    all: 'Todos',
    status: { open: 'Abierto', overdue: 'Vencido', closed: 'Cerrado', draft: 'Sin confirmar' },
    pending: (n) => `${n} ${n === 1 ? 'pendiente' : 'pendientes'}`,
    lines: (n) => `${n} ${n === 1 ? 'artículo' : 'artículos'}`,
    due: (when) => `Devolver ${when}`,
    late: (d) => (d === 0 ? 'Venció hoy' : `Venció hace ${d} ${d === 1 ? 'día' : 'días'}`),
    noPractice: 'Sin práctica',
  },

  newLoan: {
    title: 'Nuevo vale',
    borrower: 'Solicitante',
    borrowerPick: 'Elige quién se lleva el material',
    borrowerNew: 'Nuevo solicitante',
    borrowerName: 'Nombre',
    borrowerNamePh: 'Ej. Equipo 4',
    borrowerType: 'Tipo',
    borrowerGroup: 'Grupo',
    borrowerGroupPh: 'Ej. 4° A',
    borrowerId: 'Número de control',
    borrowerIdRequired: 'Número de control (obligatorio para alumnos)',
    errStudentId: 'Escribe el número de control del alumno.',
    errBorrowerName: 'Escribe el nombre del solicitante.',
    borrowerAdd: 'Agregar solicitante',
    borrowerTypes: { team: 'Equipo de práctica', student: 'Alumno', teacher: 'Docente' },
    practice: 'Práctica',
    practicePh: 'Ej. Titulación ácido-base (opcional)',
    practicePick: 'Usar una práctica guardada',
    practiceNone: 'Sin práctica guardada',
    practiceAlready: 'Esa práctica ya está en el vale; no se volvió a sumar.',
    practiceFilled: (n) => `Práctica cargada: ${n} ${n === 1 ? 'artículo' : 'artículos'}`,
    practiceShort: (names) => `No alcanza: ${names}. Revisa los renglones en rojo.`,
    practiceMissing: (n) => `${n} ${n === 1 ? 'artículo de la práctica ya no existe' : 'artículos de la práctica ya no existen'} y no se agregó.`,
    items: 'Artículos',
    scan: 'Escanear artículos',
    stopScan: 'Terminar',
    search: 'O busca por nombre o código',
    noItems: 'Escanea las etiquetas o busca los artículos que se llevan.',
    available: (q) => `hay ${q}`,
    remove: 'Quitar',
    added: (name) => `${name} agregado`,
    plusOne: (name, q) => `${name}: ${q}`,
    unknown: (code) => `No existe el código ${code}.`,
    noneLeft: (name) => `No queda ${name} en el laboratorio.`,
    equipmentOnce: (name) => `${name} ya está en el vale.`,
    confirm: 'Confirmar préstamo',
    confirmed: 'Préstamo confirmado',
    errBorrower: 'Elige o agrega un solicitante.',
    errEmpty: 'Agrega al menos un artículo.',
    errQty: 'Revisa las cantidades marcadas.',
    errStock: 'Hay artículos con menos existencia de la que pides.',
    seconds: (s) => `Capturado en ${s} s`,
    viewLoan: 'Ver vale',
    another: 'Otro vale',
    discard: 'Descartar',
    discardQ: '¿Descartar este vale sin confirmar?',
    due: 'Se devuelve',
  },

  loanDetail: {
    title: 'Vale',
    notFound: 'Ese vale no existe.',
    borrower: 'Solicitante',
    practice: 'Práctica',
    delivered: 'Entregado',
    due: 'Devolver',
    closedAt: 'Cerrado',
    captureTime: 'Tiempo de captura',
    lent: 'Prestado',
    pending: 'Pendiente',
    returned: 'Devuelto',
    lost: 'Merma',
    consumed: 'Consumido',
    returnBtn: 'Devuelto',
    lossBtn: 'Roto o perdido',
    consumeBtn: 'Consumido',
    reagentBack: 'Cantidad que regresó',
    reagentBackHelp: 'Lo que no regrese se registra como consumido.',
    reagentBtn: 'Registrar regreso',
    savedReagent: (back, used) => `Regresó ${back} · consumido ${used}`,
    lossNote: '¿Qué pasó? (opcional)',
    lossQty: 'Cantidad perdida',
    lossQtyHint: 'escribe abajo cuánto',
    reagentEmpty: 'Escribe cuánto regresó. Si no regresó nada, escribe 0.',
    lossNotePh: 'Ej. Se cayó al lavarla',
    returnAll: 'Todo regresó completo',
    returnAllQ: '¿Registrar que todo lo pendiente regresó completo?',
    lossQ: (qty, who) => `¿Registrar ${qty} como merma a cargo de ${who}?`,
    lossReason: 'Rotura o pérdida en préstamo',
    savedReturn: 'Devolución registrada',
    savedLoss: 'Merma registrada',
    savedConsume: 'Consumo registrado',
    closedToast: 'Vale cerrado: todo quedó saldado',
    badQty: 'La cantidad debe ser mayor que 0 y no más de lo pendiente.',
    history: 'Movimientos del vale',
    allSettled: 'Todo quedó saldado.',
  },

  practices: {
    title: 'Prácticas',
    intro: 'Guarda el material de cada práctica una sola vez. Al hacer un vale, eliges la práctica y la lista se llena sola.',
    empty: 'Aún no hay prácticas. Agrega la primera.',
    add: 'Nueva práctica',
    newTitle: 'Nueva práctica',
    editTitle: 'Editar práctica',
    name: 'Nombre de la práctica',
    namePh: 'Ej. Titulación ácido-base',
    teacher: 'Maestro(a)',
    teacherPh: 'Ej. Mtra. Laura Méndez (opcional)',
    lab: 'Laboratorio',
    items: 'Material',
    itemsEmpty: 'Busca y agrega el material que lleva la práctica.',
    search: 'Buscar material por nombre o código',
    count: (n) => `${n} ${n === 1 ? 'artículo' : 'artículos'}`,
    saved: 'Práctica guardada',
    archive: 'Archivar práctica',
    archived: 'Práctica archivada',
    archiveQ: '¿Archivar esta práctica? Ya no aparecerá al hacer vales. Los vales anteriores no cambian.',
    notFound: 'Esa práctica no existe.',
    errors: {
      name: 'Escribe el nombre de la práctica.',
      empty: 'Agrega al menos un artículo.',
      qty: 'Revisa las cantidades: deben ser mayores que 0.',
    },
    useInLoan: 'Hacer vale con esta práctica',
  },

  moves: {
    title: 'Registrar movimiento',
    receive: 'Recepción',
    loss: 'Merma',
    adjust: 'Ajuste por conteo',
    qty: 'Cantidad',
    counted: 'Cantidad contada',
    countedHelp: (q) => `El sistema dice ${q}. Escribe lo que contaste.`,
    note: 'Nota',
    noteReq: 'Nota (obligatoria)',
    notePh: 'Ej. Factura 123, donación, compra del plantel…',
    reason: 'Motivo',
    reasons: ['Rotura', 'Pérdida', 'Caducidad', 'Otro'],
    save: 'Registrar',
    savedReceive: 'Recepción registrada',
    savedLoss: 'Merma registrada',
    savedAdjust: (d) => `Ajuste registrado (${d})`,
    noChange: 'El conteo coincide: no hay nada que ajustar.',
    errQty: 'Escribe una cantidad mayor que 0.',
    errCount: 'Escribe la cantidad contada (puede ser 0).',
    errNote: 'El ajuste necesita una nota que explique la diferencia.',
    errLoss: 'No hay tanta existencia en el laboratorio.',
    equipmentNote: 'El equipo es pieza única: se presta desde un vale y se da de baja con una merma.',
  },

  items: {
    title: 'Artículos',
    empty: 'Aún no hay artículos. Carga la demo o agrega el primero.',
    noResults: 'Ningún artículo coincide. Cambia la búsqueda o quita filtros.',
    search: 'Buscar por nombre, código o dato',
    filterLab: 'Laboratorio',
    filterLocation: 'Ubicación',
    filterKind: 'Tipo',
    low: 'Bajo mínimo',
    expiring: 'Por caducar',
    archived: 'Archivados',
    count: (n) => `${n} ${n === 1 ? 'artículo' : 'artículos'}`,
    add: 'Agregar artículo',
    clear: 'Quitar filtros',
  },

  stock: {
    inLab: 'en lab',
    lent: 'prestados',
    total: 'total',
    min: 'mín',
    inPlace: 'En su lugar',
    lentTo: (who) => `Prestado a ${who}`,
    lentUnknown: 'Prestado',
    lost: 'Dado de baja',
    low: 'Bajo mínimo',
    expired: 'Caducado',
    expiring: 'Por caducar',
  },

  itemCard: {
    title: 'Ficha del artículo',
    notFound: (code) => `No existe un artículo con el código ${code}. Revisa la etiqueta o escríbelo a mano.`,
    data: 'Datos',
    lab: 'Laboratorio',
    location: 'Ubicación',
    serial: 'Número de serie',
    expires: 'Caduca',
    notes: 'Notas',
    extra: 'Especificaciones',
    extraEmpty: 'Sin especificaciones. Agrega las que pida el maestro: marca, modelo, concentración…',
    extraKey: 'Dato',
    extraValue: 'Valor',
    extraAdd: 'Agregar dato',
    extraSaved: 'Dato guardado',
    extraRemoved: 'Dato quitado',
    history: 'Historial',
    historyEmpty: 'Sin movimientos todavía.',
    by: (who) => `Responsable: ${who}`,
    loan: (practice) => `Vale: ${practice}`,
    printLabel: 'Imprimir etiqueta',
    photo: 'Foto',
    photoAdd: 'Tomar o elegir foto',
    photoChange: 'Cambiar foto',
    photoRemove: 'Quitar foto',
    photoSaved: 'Foto guardada',
    photoRemoved: 'Foto quitada',
    photoError: 'No se pudo leer la imagen. Prueba con otra foto.',
    archive: 'Archivar',
    unarchive: 'Quitar de archivados',
    archivedNote: 'Artículo archivado: no aparece en la lista ni en los conteos.',
    archiveQ: '¿Archivar este artículo? Deja de aparecer en la lista, pero su historial se conserva.',
    archivedToast: 'Artículo archivado',
    unarchivedToast: 'Artículo de regreso en la lista',
    deleteQ: '¿Eliminar este artículo? No tiene movimientos, así que se borra por completo.',
    deletedToast: 'Artículo eliminado',
  },

  itemForm: {
    newTitle: 'Nuevo artículo',
    editTitle: 'Editar artículo',
    name: 'Nombre',
    namePh: 'Ej. Vaso de precipitado 250 ml',
    kind: 'Tipo',
    lab: 'Laboratorio',
    location: 'Ubicación',
    unit: 'Unidad',
    initialQty: 'Cantidad que hay hoy',
    initialQtyHelp: 'Se registra como recepción. Después, la existencia solo cambia con movimientos.',
    unitLocked: 'La unidad ya no cambia: el historial está registrado en ella.',
    minStock: 'Mínimo',
    minStockHelp: 'Si la existencia baja de aquí, se marca en rojo. Deja 0 si no aplica.',
    expiresAt: 'Fecha de caducidad',
    serial: 'Número de serie',
    notes: 'Notas',
    codeNote: (code) => `Código ${code}. No cambia porque va impreso en la etiqueta.`,
    codeNew: (prefix) => `El código se genera solo: ${prefix}-0000.`,
    needLab: 'Primero agrega un laboratorio en Ajustes.',
    goSettings: 'Ir a Ajustes',
    errName: 'Escribe el nombre del artículo.',
    errQty: 'Escribe una cantidad válida, por ejemplo 12 o 2.5.',
    saved: 'Artículo guardado',
    created: (code) => `Artículo ${code} agregado`,
  },

  settings: {
    title: 'Ajustes',
    labs: 'Laboratorios',
    labName: 'Nombre',
    labNamePh: 'Ej. Química',
    labPrefix: 'Prefijo',
    labPrefixPh: 'QUI',
    labPrefixHelp: 'De 2 a 5 letras. Va al inicio de cada código (QUI-0001).',
    labPrefixLocked: 'El prefijo ya no cambia: hay artículos con etiquetas impresas.',
    addLab: 'Agregar laboratorio',
    labSaved: 'Laboratorio guardado',
    labDeleteQ: '¿Eliminar este laboratorio y sus ubicaciones?',
    labDeleted: 'Laboratorio eliminado',
    labInUse: 'Ese laboratorio tiene artículos. Muévelos o archívalos antes de eliminarlo.',
    errLab: 'Escribe el nombre y un prefijo de 2 a 5 letras.',
    errPrefixTaken: 'Ese prefijo ya lo usa otro laboratorio.',
    locations: 'Ubicaciones',
    locationPh: 'Ej. Anaquel B · Gaveta 2',
    addLocation: 'Agregar ubicación',
    locationSaved: 'Ubicación guardada',
    locationDeleted: 'Ubicación eliminada',
    locationInUse: 'Esa ubicación tiene artículos. Cámbialos de lugar antes de eliminarla.',
    noLabs: 'Aún no hay laboratorios. Agrega el primero o carga la demo.',
    loanDays: 'Días de préstamo por defecto',
    loanDaysHelp: '0 = se devuelve el mismo día.',
    loanDaysSaved: 'Días de préstamo guardados',
    demo: 'Datos de demostración',
    demoHelp: 'Crea Química y Biología con 33 artículos, 5 solicitantes y 3 vales para enseñar la app.',
    demoLoad: 'Cargar datos de demostración',
    demoOnlyEmpty: 'La demo solo se carga con la app vacía. Usa "Borrar todo" primero.',
    demoLoaded: (n) => `Demo cargada: ${n} artículos`,
    wipe: 'Borrar todo',
    wipeHelp: 'Elimina todos los datos de este dispositivo. No se puede deshacer.',
    wipeType: 'Escribe BORRAR para confirmar',
    wipeWord: 'BORRAR',
    wipeQ: '¿Borrar todos los datos de este dispositivo? No se puede deshacer.',
    wipeConfirm: 'Borrar todos los datos',
    wipeDone: 'Se borraron todos los datos',
    storage: 'Datos en este dispositivo',
    storageReady: 'Base de datos lista',
    storageError: 'No se pudo abrir la base de datos. Cierra otras pestañas de C-Lab y vuelve a abrirla.',
    offlineReady: 'Lista para usarse sin internet',
    update: 'Buscar actualización',
    updateHelp: 'Si falta una pantalla nueva, toca aquí con internet. La app se recarga sola si hay versión nueva.',
    updateNone: 'Ya tienes la versión más reciente.',
    updateOffline: 'Sin internet no se puede buscar una versión nueva.',
    offlinePending: 'Preparando uso sin internet…',
  },

  board: {
    title: 'Tablero',
    menu: 'Tablero de exposición',
    loading: 'Cargando tablero…',
    empty: 'Aún no hay datos. Carga la demo para ver el tablero.',
    lab: (name) => `Laboratorio ${name}`,
    openLoans: (n) => `${n} ${n === 1 ? 'vale abierto' : 'vales abiertos'}`,
    noLoans: 'Todo el material está en su lugar.',
    recent: 'Últimos movimientos',
    error: 'No se pudo leer la base de datos.',
  },

  backup: {
    title: 'Respaldo',
    why: 'Los datos viven solo en este dispositivo. Si se pierde o se borra el navegador, solo el respaldo los recupera.',
    last: (when) => `Último respaldo: ${when}`,
    never: 'Aún no has hecho un respaldo.',
    full: 'Respaldo completo',
    download: 'Descargar respaldo',
    share: 'Compartir respaldo',
    shareHelp: 'Compartir te deja mandarlo por WhatsApp, correo o Drive.',
    downloaded: 'Respaldo descargado',
    restore: 'Restaurar desde archivo',
    restoreHelp: 'Reemplaza TODOS los datos de este dispositivo por los del archivo.',
    restoreQ: (s) => `¿Reemplazar todo por el respaldo del ${s.when}? Trae ${s.items} artículos, ${s.loans} vales y ${s.movements} movimientos. Lo actual se pierde.`,
    restored: 'Respaldo restaurado',
    errors: {
      notJson: 'Ese archivo no se pudo leer. Elige un archivo .json de C-Lab.',
      notLabqr: 'Ese archivo no es un respaldo de C-Lab.',
      version: 'Ese respaldo es de otra versión de C-Lab.',
      missingTable: 'El respaldo está incompleto.',
      badRows: 'El respaldo tiene datos dañados.',
    },
    csv: 'Exportar a Excel (CSV)',
    csvHelp: 'Para revisar en la computadora o entregar reportes.',
    csvInventory: 'Inventario actual',
    csvMovements: 'Movimientos',
    csvLoans: 'Vales',
    importTitle: 'Importar inventario inicial',
    importHelp: 'Llena la plantilla en Excel, guárdala como CSV y elígela aquí. Crea laboratorios, ubicaciones y artículos que no existan.',
    template: 'Descargar plantilla',
    chooseCsv: 'Elegir archivo CSV',
    preview: (ok, bad) => `${ok} ${ok === 1 ? 'artículo listo' : 'artículos listos'} para importar${bad ? ` · ${bad} ${bad === 1 ? 'renglón con error' : 'renglones con error'}` : ''}.`,
    lineError: (line, msg) => `Renglón ${line}: ${msg}`,
    importBtn: (n) => `Importar ${n} ${n === 1 ? 'artículo' : 'artículos'}`,
    imported: (n) => `${n} artículos importados`,
    persistOk: 'El navegador protege estos datos: no los borra para liberar espacio.',
    persistNo: 'El navegador podría borrar estos datos si se llena el almacenamiento. Instala la app y haz respaldos seguido.',
    reminder: 'Haz un respaldo: tu último fue hace más de 7 días.',
    reminderNever: 'Aún no hay respaldo de estos datos. Haz uno para no perderlos.',
    reminderBtn: 'Respaldar',
  },

  pending: {
    title: 'En construcción',
    body: 'Esta pantalla llega en una fase siguiente.',
  },

  notFound: {
    title: 'Página no encontrada',
    body: 'Esa dirección no existe en C-Lab.',
    back: 'Ir a Inicio',
  },

  version: (v, built) => `Versión ${v} · ${built}`,
};
